# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 08:07
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category_title', models.CharField(max_length=255, verbose_name='Категория')),
                ('category_image', models.ImageField(blank=True, default='', upload_to='categories')),
                ('category_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Описание категории')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.Category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('comment_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('post_title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('post_description', models.CharField(blank=True, default='', max_length=170, verbose_name='META DESC')),
                ('post_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Текст поста')),
                ('post_image', models.ImageField(blank=True, default='', upload_to='posts/post_created-%Y-%m-%d', verbose_name='Главное изображение')),
                ('post_active', models.BooleanField(default=True, verbose_name='Вкл/Выкл')),
                ('post_category', mptt.fields.TreeForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_parent', to='blog.Post', verbose_name='Пост коментария'),
        ),
    ]
