# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_parent',
            new_name='parent',
        ),
    ]
