# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 10:28
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170715_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=mptt.fields.TreeForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
    ]
