# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogproduct',
            name='feature',
            field=models.ManyToManyField(blank=True, default=None, to='feature.Feature', verbose_name='Характеристика'),
        ),
    ]
