# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogproduct',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.CatalogCurrency', verbose_name='Валюта'),
        ),
    ]
