# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170725_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogproduct',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.CatalogCategory'),
        ),
        migrations.AlterField(
            model_name='catalogproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='catalogproduct',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, null=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='catalogproduct',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feature.Unit', verbose_name='Единица измерения'),
        ),
    ]
