# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170719_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeature',
            name='unit',
        ),
    ]
