# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0002_auto_20170719_2239'),
        ('catalog', '0005_remove_productfeature_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeature',
            name='unit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feature.Unit', verbose_name='Единица измерения'),
        ),
    ]
