# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productfeature_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeature',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Значение'),
        ),
    ]
