# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20170720_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogcategory',
            name='slug',
            field=models.SlugField(default='', max_length=255, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='slug',
            field=models.SlugField(default='', max_length=255, verbose_name='Слаг'),
        ),
    ]
