# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20170722_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogproduct',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='catalog/product_created-%Y-%m-%d', verbose_name='Изображение'),
        ),
    ]
