# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_catalogproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogimage',
            name='is_main',
        ),
    ]
