# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20170723_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='count',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Количество'),
        ),
    ]
